export type DocPage = {
  category: string
  title: string
  href: string
  description: string
  keywords: string[]
}

export const docPages: DocPage[] = [
  {
    category: "Getting Started",
    title: "Introduction",
    href: "/",
    description: "Overview of Flutter Reactive and its core value proposition.",
    keywords: [
      "home",
      "overview",
      "start",
      "getting started",
      "reactive state",
      "state management",
      "flutter state",
      "package overview",
      "intro",
      "lightweight",
      "reactive system",
      "no boilerplate",
      "setState",
      "local state",
      "shared state",
      "derived state",
      "automatic rebuilds",
      "flutter docs",
      "concepts",
      "examples",
      "faq",
      "installation",
      "use cases",
      "store",
      "binding",
      "validation",
      "transactions",
      "dependencies",
      "performance",
      "zero dependencies",
    ],
  },
  {
    category: "Getting Started",
    title: "Installation",
    href: "/installation",
    description: "Install the package and import the main entrypoint.",
    keywords: [
      "setup",
      "install",
      "pub get",
      "pub add",
      "import",
      "pubspec",
      "dependency",
      "getting started",
      "flutter pub",
      "dart pub",
      "package install",
      "add dependency",
      "first step",
      "install guide",
      "local package",
      "version",
      "setup guide",
      "pubspec.yaml",
      "import statement",
      "terminal",
      "command line",
      "manual install",
      "dependency management",
      "package setup",
      "sdk",
      "version pinning",
      "import flutter reactive",
      "install package",
      "quick install",
      "prerequisites",
    ],
  },
  {
    category: "Concepts",
    title: "Reactive & ReactiveN",
    href: "/concepts/reactive",
    description: "Learn the base reactive container and its nullable variant.",
    keywords: [
      "Reactive<T>",
      "ReactiveN<T>",
      "reactive",
      "nullable reactive",
      "non-nullable",
      "nullable",
      "rt",
      "rtNonStrict",
      "reactive value",
      "observable",
      "state holder",
      "value container",
      "strict mode",
      "non-strict",
      "initial value",
      "no initial value",
      "dynamic state",
      "base concept",
      "core API",
      "read only",
      "mutation",
      "listen",
      "notify",
      "bind",
      "auto bind",
      "dart object",
      "nullable state",
      "value updates",
      "strict equality",
      "local state",
      "global state",
    ],
  },
  {
    category: "Concepts",
    title: "Binding & Widgets",
    href: "/concepts/binding",
    description: "Bind values to widgets, listen to changes, and use builders.",
    keywords: [
      "react()",
      "reactN()",
      "bind",
      "unbind",
      "ReactiveBuilder",
      "Rxb",
      "Rxsb",
      "widget binding",
      "state binding",
      "listen",
      "stream builder",
      "updateState",
      "setState replacement",
      "automatic rebuild",
      "manual binding",
      "listener",
      "unsubscribe",
      "StatefulWidget",
      "StatelessWidget",
      "builder",
      "rebuild",
      "local widget state",
      "current state",
      "sync UI",
      "stream listen",
      "widget updates",
      "event callback",
      "state update",
      "reactive widget",
      "auto rebuild",
      "view binding",
    ],
  },
  {
    category: "Concepts",
    title: "Validation",
    href: "/concepts/validation",
    description: "Validate values inline with require() and handle errors.",
    keywords: [
      "ReactiveValidatorError",
      "require",
      "guard",
      "form validation",
      "input validation",
      "rules",
      "constraints",
      "error message",
      "submit validation",
      "field validation",
      "input guard",
      "validation rule",
      "invalid input",
      "try catch",
      "synchronous error",
      "email validation",
      "password validation",
      "range check",
      "positive value",
      "min max",
      "validation chain",
      "reject value",
      "throw error",
      "form field",
      "user input",
      "data validation",
      "validator",
      "error state",
      "constraint",
      "safe input",
      "guardrail",
    ],
  },
  {
    category: "Concepts",
    title: "Derived State",
    href: "/concepts/derived",
    description: "Build computed and combined state from reactive sources.",
    keywords: [
      "as",
      "combine",
      "compute",
      "derived",
      "derived state",
      "computed",
      "read-only",
      "combine2",
      "combine3",
      "combine4",
      "combine5",
      "formula",
      "derived value",
      "computed value",
      "transformation",
      "aggregation",
      "sum",
      "total",
      "summary",
      "dependency tracking",
      "auto recompute",
      "combine sources",
      "map value",
      "format label",
      "price total",
      "cart subtotal",
      "dynamic dependency",
      "reactive math",
      "computed state",
      "readonly derived",
      "computed label",
    ],
  },
  {
    category: "Concepts",
    title: "Transactions",
    href: "/concepts/transactions",
    description: "Group updates and rollback safely when something fails.",
    keywords: [
      "rollback",
      "save",
      "restore",
      "run",
      "checkpoint",
      "transaction",
      "atomic updates",
      "undo",
      "cancel edit",
      "rollbackOnError",
      "transactional update",
      "commit",
      "revert",
      "snapshot",
      "draft state",
      "restore point",
      "error recovery",
      "batch update",
      "all or nothing",
      "manual rollback",
      "automatic rollback",
      "transaction manager",
      "state snapshot",
      "safe update",
      "cancel flow",
      "multi step change",
      "rollback changes",
      "atomic write",
      "undo action",
      "checkpoint restore",
    ],
  },
  {
    category: "Concepts",
    title: "Dependencies",
    href: "/concepts/dependencies",
    description: "Cache and reuse shared stores with ReactiveDependency.",
    keywords: [
      "RxDep",
      "dep",
      "dependency",
      "store",
      "service",
      "inject",
      "shared store",
      "service locator",
      "singleton",
      "cache",
      "shared store",
      "app state",
      "global store",
      "reuse instance",
      "create once",
      "lifecycle hooks",
      "onCreate",
      "onDispose",
      "registry",
      "service object",
      "cache lookup",
      "drop",
      "clear",
      "use factory",
      "dependency registry",
      "store reuse",
      "shared service",
      "state service",
      "inject store",
      "cache service",
    ],
  },
  {
    category: "Use Cases",
    title: "Practical Workflows",
    href: "/use-cases",
    description: "Concrete scenarios for forms, listen/cancel flows, undo, and rollback.",
    keywords: [
      "use cases",
      "workflow",
      "listen",
      "cancel",
      "undo",
      "real-world",
      "practical",
      "how to",
      "step by step",
      "listen cancel",
      "save restore",
      "example workflow",
      "real world",
      "rollback flow",
      "search debounce",
      "form flow",
      "edit flow",
      "cancel action",
      "change tracking",
      "side effect",
      "trigger action",
      "guided usage",
      "implementation pattern",
      "best practice",
      "copy paste",
      "recipe",
      "scenario",
      "guide",
      "undo flow",
      "practical guide",
    ],
  },
  {
    category: "Examples",
    title: "Simple Counter",
    href: "/examples/counter",
    description: "Basic counter with increment, decrement, and validation.",
    keywords: [
      "counter",
      "inc",
      "dec",
      "reset",
      "increment",
      "decrement",
      "validation",
      "button",
      "example",
      "statefulwidget",
      "reactive counter",
      "increment button",
      "decrement button",
      "reset button",
      "simple example",
      "starter example",
      "beginner",
      "number",
      "tap",
      "ui update",
      "counting",
      "reactive value",
      "state binding",
      "demo",
      "tutorial",
      "basic counter",
      "counter page",
      "floating action button",
      "counter demo",
      "first example",
    ],
  },
  {
    category: "Examples",
    title: "Form with Validation",
    href: "/examples/form",
    description: "A sign-up form with real-time validation and error handling.",
    keywords: [
      "form",
      "validation",
      "input",
      "submit",
      "signup",
      "password",
      "email",
      "error handling",
      "real-time",
      "sign up",
      "signup form",
      "text field",
      "email field",
      "password field",
      "confirm password",
      "checkbox",
      "submit button",
      "live validation",
      "field errors",
      "auth form",
      "client side validation",
      "form state",
      "button disabled",
      "reactive form",
      "input change",
      "error text",
      "user onboarding",
      "credentials",
      "registration",
      "create account",
    ],
  },
  {
    category: "Examples",
    title: "Todo List",
    href: "/examples/todo",
    description: "Add, filter, and manage a todo list with derived stats.",
    keywords: [
      "todo",
      "list",
      "filter",
      "items",
      "task",
      "derived stats",
      "add item",
      "remove item",
      "complete",
      "tasks",
      "task list",
      "filtering",
      "active items",
      "completed items",
      "statistics",
      "derived counts",
      "toggle item",
      "clear completed",
      "bulk toggle",
      "list state",
      "todo page",
      "item count",
      "checklist",
      "manage tasks",
      "compute stats",
      "reactive list",
      "filter chips",
      "todo example",
      "task manager",
      "item filters",
    ],
  },
  {
    category: "Examples",
    title: "Shopping Cart",
    href: "/examples/cart",
    description: "Cart totals, discounts, and transactional checkout flow.",
    keywords: [
      "cart",
      "checkout",
      "discount",
      "total",
      "subtotal",
      "tax",
      "coupon",
      "transaction",
      "pricing",
      "shopping cart",
      "apply coupon",
      "remove item",
      "quantity",
      "stock",
      "inventory",
      "order total",
      "checkout flow",
      "purchase",
      "billing",
      "payment",
      "invoice",
      "cart state",
      "sales",
      "ecommerce",
      "pricing calculator",
      "promo code",
      "basket",
      "shipping",
      "order summary",
      "checkout example",
    ],
  },
  {
    category: "Resources",
    title: "FAQ",
    href: "/faq",
    description: "Find answers to common questions and troubleshooting steps.",
    keywords: [
      "questions",
      "help",
      "troubleshooting",
      "listen",
      "cancel",
      "listen cancel",
      "rollback",
      "validation error",
      "ui not updating",
      "disposed",
      "?",
      "faq",
      "common questions",
      "answer",
      "debug",
      "unsubscribe",
      "mounted",
      "strict mode",
      "mutate",
      "validator error",
      "transaction rollback",
      "save restore",
      "diagnostic",
      "how do i",
      "why is my ui not updating",
      "why is it disposed",
      "listen later",
      "cancel later",
      "help center",
      "troubleshoot",
      "issue",
    ],
  },
]
